project:
  type: website
  output-dir: docs
  resources:
    - files/*

website:
  title: "My Website"
  site-url: "https://rsm-sharwalkar.github.io/Marketing_Analytics/"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: Blog.qmd
        text: Blogs
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-summary: "Code"
